apiVersion: apps/v1
kind: Deployment
metadata:
  name: functionapp
  labels:
    app: functionapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: functionapp
  template:
    metadata:
      labels:
        app: functionapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "functionapp"
        dapr.io/port: "3001"
    spec:
      containers:
      - name: functionapp
        image: dapriosamples/dotnet-azurefunction
        ports:
        - containerPort: 3001
        imagePullPolicy: Always
        env:
        - name: StateStoreName
          value: statestore
        - name: KafkaBindingName
          value: sample-topic