apiVersion: apps/v1
kind: Deployment
metadata:
  name: functionapp
  labels:
    app: functionapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: functionapp
  template:
    metadata:
      labels:
        app: functionapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "functionapp"
        dapr.io/app-port: "3001"
    spec:
      containers:
      - name: functionapp
        image: dapriosamples/dotnet-azurefunction:edge
        ports:
        - containerPort: 3001
        imagePullPolicy: Always
        env:
        - name: StateStoreName
          value: statestore
        - name: KafkaBindingName
          value: sample-topic
        - name: PubSubName
          value: pubsub
---
apiVersion: v1
kind: Service
metadata:
  name: functionapp
spec:
  selector:
    app: functionapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer