apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sample-topic
  namespace: default
spec:
  type: bindings.kafka
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: "dapr-kafka.default.svc.cluster.local:9092" #localhost:9092 - for local kafka
  # consumer configuration: topic and consumer group
  - name: topics
    value: sample
  - name: consumerGroup
    value: group1
  # publisher configuration: topic
  - name: publishTopic
    value: sample
  - name: authRequired
    value: "false" 