coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 80%
        # base: auto 
        # flags: 
        #   - unit
        # paths: 
        #   - "src"