apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: <your-redis-host-name>
  - name: redisPassword
    value: <your-redis-password>