apiVersion: v1
kind: Service
metadata:
  name: azure-function
  namespace: default
spec:
  selector:
    app: azure-function
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-function
  namespace: default
  labels:
    app: azure-function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-function
  template:
    metadata:
      labels:
        app: azure-function
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "functionapp"
        # Only define port if Dapr triggers are included
        dapr.io/port: "3001"
    spec:
      containers:
      - name: azure-function
        image: jeffhollan/dapr-function
        ports:
        # Port for HTTP triggered functions
        - containerPort: 80
---

