apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: 0.tcp.in.ngrok.io:19904
  - name: redisPassword
    value: ""
