name: Code Coverage

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
      - release-*
    paths-ignore:
      - "**.md"
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and test
        run: dotnet test --collect:"XPlat Code Coverage"

  code-coverage:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install report generator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate code coverage report
        run: dotnet test --collect:"XPlat Code Coverage" --logger trx

      - name: Convert coverage report to Cobertura format
        run: dotnet reportgenerator "-reports:**/*.trx" "-targetdir:coverage" "-reporttypes:Cobertura"

      - name: Publish code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage
          path: coverage